# https://docs.lando.dev/plugins/symfony/config.html

name: docker-sdk-bundle
recipe: symfony
config:
  webroot: ./symfony/public
  php: '8.0'
  via: nginx
services:
  node:
    type: node:18
tooling:
  node:
    service: node
  yarn:
    service: node
